---
# Configure SNMP Monitoring Playbook
# Configures SNMP monitoring on network devices
# Supports multiple platforms: Cisco IOS/NX-OS, Arista EOS, Juniper JunOS

- name: Configure SNMP Monitoring
  hosts: localhost
  gather_facts: false
  vars:
    target_host: "{{ target_host }}"
    device_name: "{{ device_name }}"
    platform: "{{ platform }}"
    snmp_version: "{{ snmp_version | default('v2c') }}"
    snmp_community: "{{ snmp_community | default('public') }}"
    snmp_collector_ip: "{{ snmp_collector_ip }}"
    monitoring_scope: "{{ monitoring_scope }}"
    
  tasks:
    - name: Display SNMP configuration information
      debug:
        msg: |
          Configuring SNMP Monitoring:
          Device: {{ device_name }} ({{ target_host }})
          Platform: {{ platform }}
          SNMP Version: {{ snmp_version }}
          Community: {{ snmp_community }}
          Collector: {{ snmp_collector_ip }}

    - name: Configure SNMP (Cisco IOS)
      block:
        - name: Configure SNMP community and access
          cisco.ios.ios_config:
            lines:
              - "snmp-server community {{ snmp_community }} RO"
              - "snmp-server host {{ snmp_collector_ip }} version {{ snmp_version }} {{ snmp_community }}"
              - "snmp-server enable traps"
              - "snmp-server enable traps snmp linkdown linkup coldstart warmstart"
              - "snmp-server enable traps entity"
              - "snmp-server enable traps envmon"
              - "snmp-server enable traps config"
              - "snmp-server contact Network Operations {{ monitoring_scope }}"
              - "snmp-server location {{ monitoring_scope }} Datacenter"
            save_when: changed
          delegate_to: "{{ target_host }}"
          register: ios_snmp_config
          
        - name: Configure SNMP system information (IOS)
          cisco.ios.ios_config:
            lines:
              - "snmp-server chassis-id {{ device_name }}"
            save_when: changed
          delegate_to: "{{ target_host }}"
          
      when: platform == "ios"

    - name: Configure SNMP (Arista EOS)
      block:
        - name: Configure SNMP on EOS device
          arista.eos.eos_config:
            lines:
              - "snmp-server community {{ snmp_community }} ro"
              - "snmp-server host {{ snmp_collector_ip }} version {{ snmp_version }} {{ snmp_community }}"
              - "snmp-server enable traps"
              - "snmp-server enable traps bgp"
              - "snmp-server enable traps entity arista-ent-sensor-alarm"
              - "snmp-server enable traps snmp link-change"
              - "snmp-server contact Network-Operations-{{ monitoring_scope }}"
              - "snmp-server location {{ monitoring_scope }}-Network"
            save_when: changed
          delegate_to: "{{ target_host }}"
          register: eos_snmp_config
          
      when: platform == "eos"

    - name: Configure SNMP (Cisco NX-OS)
      block:
        - name: Configure SNMP on NX-OS device
          cisco.nxos.nxos_config:
            lines:
              - "snmp-server community {{ snmp_community }} group network-operator"
              - "snmp-server host {{ snmp_collector_ip }} traps version {{ snmp_version }} {{ snmp_community }}"
              - "snmp-server enable traps"
              - "snmp-server enable traps link cisco-xcvr-mon-status-chg"
              - "snmp-server enable traps entity"
              - "snmp-server enable traps license"
              - "snmp-server enable traps feature-control"
              - "snmp-server contact Network-Operations-{{ monitoring_scope }}"
              - "snmp-server location {{ monitoring_scope }}-Datacenter"
            save_when: changed
          delegate_to: "{{ target_host }}"
          register: nxos_snmp_config
          
      when: platform == "nxos"

    - name: Configure SNMP (Juniper JunOS)
      block:
        - name: Configure SNMP on JunOS device
          junipernetworks.junos.junos_config:
            lines:
              - "set snmp community {{ snmp_community }} authorization read-only"
              - "set snmp trap-group {{ monitoring_scope }} version {{ snmp_version }}"
              - "set snmp trap-group {{ monitoring_scope }} targets {{ snmp_collector_ip }}"
              - "set snmp contact Network-Operations-{{ monitoring_scope }}"
              - "set snmp location {{ monitoring_scope }}-Network"
              - "set snmp trap-options source-address {{ ansible_host }}"
            format: set
            comment: "SNMP monitoring configuration for {{ monitoring_scope }}"
          delegate_to: "{{ target_host }}"
          register: junos_snmp_config
          
        - name: Commit JunOS SNMP configuration
          junipernetworks.junos.junos_config:
            comment: "Commit SNMP configuration for {{ device_name }}"
            confirm: 5
          delegate_to: "{{ target_host }}"
          
      when: platform == "junos"

    - name: Test SNMP connectivity
      block:
        - name: Test SNMP walk from collector (if possible)
          command: snmpwalk -v{{ snmp_version }} -c {{ snmp_community }} {{ target_host }} 1.3.6.1.2.1.1.1
          register: snmp_test
          delegate_to: localhost
          ignore_errors: true
          when: snmp_version in ['1', 'v1', '2c', 'v2c']
          
        - name: Report SNMP test results
          debug:
            msg: |
              SNMP Connectivity Test:
              Status: {{ 'SUCCESS' if snmp_test.rc == 0 else 'FAILED' }}
              {{ snmp_test.stdout if snmp_test.rc == 0 else snmp_test.stderr | default('Test skipped or failed') }}
          when: snmp_test is defined
          
      rescue:
        - name: SNMP test failed - continuing
          debug:
            msg: "Warning: SNMP connectivity test failed, but configuration was applied"

    - name: Verify SNMP configuration
      block:
        - name: Check SNMP configuration (IOS)
          cisco.ios.ios_command:
            commands:
              - "show snmp community"
              - "show snmp host"
              - "show snmp"
          delegate_to: "{{ target_host }}"
          register: ios_snmp_status
          when: platform == "ios"
          
        - name: Check SNMP configuration (EOS)
          arista.eos.eos_command:
            commands:
              - "show snmp community"
              - "show snmp host"
          delegate_to: "{{ target_host }}"
          register: eos_snmp_status
          when: platform == "eos"
          
        - name: Check SNMP configuration (NX-OS)
          cisco.nxos.nxos_command:
            commands:
              - "show snmp community"
              - "show snmp host"
          delegate_to: "{{ target_host }}"
          register: nxos_snmp_status
          when: platform == "nxos"
          
        - name: Check SNMP configuration (JunOS)
          junipernetworks.junos.junos_command:
            commands:
              - "show configuration snmp"
              - "show snmp mib walk 1.3.6.1.2.1.1.1"
            format: text
          delegate_to: "{{ target_host }}"
          register: junos_snmp_status
          when: platform == "junos"

    - name: Generate SNMP configuration report
      set_fact:
        snmp_config_report:
          device_name: "{{ device_name }}"
          platform: "{{ platform }}"
          snmp_version: "{{ snmp_version }}"
          collector_ip: "{{ snmp_collector_ip }}"
          configuration_applied: "{{ (ios_snmp_config.changed | default(false)) or (eos_snmp_config.changed | default(false)) or (nxos_snmp_config.changed | default(false)) or (junos_snmp_config.changed | default(false)) }}"
          monitoring_scope: "{{ monitoring_scope }}"
          configuration_timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Display SNMP configuration results
      debug:
        msg: |
          SNMP Configuration Results
          =========================
          Device: {{ snmp_config_report.device_name }}
          Platform: {{ snmp_config_report.platform }}
          SNMP Version: {{ snmp_config_report.snmp_version }}
          Collector IP: {{ snmp_config_report.collector_ip }}
          Configuration Applied: {{ snmp_config_report.configuration_applied | upper }}
          Monitoring Scope: {{ snmp_config_report.monitoring_scope }}
          Configured at: {{ snmp_config_report.configuration_timestamp }}
          Status: SUCCESS

    - name: Set SNMP success facts
      set_fact:
        snmp_configuration_success: true
        snmp_monitoring_active: true
        snmp_timestamp: "{{ ansible_date_time.iso8601 }}"
